let mapleader=','
colors railscasts

set shiftwidth=2
set tabstop=2
set softtabstop=2
set whichwrap=<,>,h,l,[,]
set ignorecase
set smartcase
set scrolljump=5
set scrolloff=3
set history=50
set ruler
set showcmd
set incsearch
set showmatch
set number
set nofoldenable
set backspace=indent,eol,start "untab
set expandtab
autocmd FileType make setlocal noexpandtab
set t_Co=256
set foldmethod=syntax

if exists('+colorcolumn')
  set colorcolumn=80
  hi colorcolumn guibg=gray14 ctermbg=darkgray
endif

"set guifont=dina\ 12
set guifont=monaco\ 12
set mouse=a
if &t_Co > 2 || has("gui_running")
  syntax on
  set hlsearch
endif

if has("autocmd")
  filetype plugin indent on
  augroup vimrcEx
  au!
  autocmd FileType text setlocal textwidth=78
  autocmd BufReadPost *
    \ if line("'\"") > 1 && line("'\"") <= line ("$") |
    \   exe "normal! g`\"" |
    \ endif

  augroup END
else
  set autoindent
endif "has("autocmd")

if !exists(":DiffOrig")
  command DiffOrig vert new | set bt=nofile | r # | 0d_ | diffthis
      \ | wincmd p | diffthis
endif

hi ExtraWhitespace ctermbg=darkblue guibg=darkblue
autocmd Syntax * syn match ExtraWhitespace /\s\+$\| \+\ze\t/ containedin=ALL

"ms-word
autocmd BufReadPre *.doc set ro
autocmd BufReadPre *.doc set hlsearch!
autocmd BufReadPost *.doc %!antiword "%"

"avoid auto indent
set pastetoggle=<F10>

"line navigation
noremap <Up> gk
noremap <Down> gj
nnoremap j gj
nnoremap gj j
nnoremap gk k
nnoremap k gk

"clear search results
nnoremap <CR> :nohlsearch<CR><CR>

"tabs
nnoremap t0 :tabfirst<CR>
nnoremap t^ :tabfirst<CR>
nnoremap t$ :tablast<CR>
nnoremap tH :tabfirst<CR>
nnoremap tL :tablast<CR>
nnoremap th :tabprev<CR>
nnoremap tl :tabnext<CR>
nnoremap tn :tabnext<Space>
nnoremap tp :tabprev<Space>
nnoremap te :tabedit<Space>
nnoremap tm :tabmove<Space>
nnoremap td :tabdo<Space>
nnoremap tc :tabclose<CR>
nnoremap to :tabonly<CR>

"latex
set grepprg=grep\ -nH\ $*
let g:tex_flavor = "latex"
set runtimepath=~/.vim,$VIM/vimfiles,$VIMRUNTIME,$VIM/vimfiles/after,~/.vim/after

"spell checking
set spell spelllang=en_us
set spellfile=~/.vim/spell/en.utf-8.add
hi SpellBad term=reverse ctermfg=white ctermbg=60 guifg=#ffffff guibg=#7f0000 gui=underline
hi SpellCap guifg=#ffffff guibg=#7f007f
hi SpellRare guifg=#ffffff guibg=#00007f gui=underline
hi SpellLocal term=reverse ctermfg=black ctermbg=darkgreen guifg=#ffffff guibg=#7f0000 gui=underline

"trailing space
function! StripSpace()
  let mypos = getpos('.')
  let myreg = getreg('/')
  :%s/\s\+$//
  call setpos('.', mypos)
  call setreg('/', myreg)
endfunction
noremap <leader>ss :call StripSpace()<CR>
